Добавлена базовая реализация метода POST для создание типов документов
Alexandr-Kokorin/CaseLabProject pull request #13
Opened 2024-10-03 20:49 UTC by maksim25y

Добавлен репозиторий для работы с типами документов
Добавлен сервис с базовой реализацией crud методов для работы с типами документов
Добавлен контроллер с базовой реализацией POST запроса для добавления новых типов документов

2024-10-03 21:22 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/service/DocumentTypesService.java
> +
Ты можешь повесить аннотацию @AllArgsConstructor на класс и вообще убрать конструктор, суть получается та же, но чуть более сладко)

2024-10-04 09:13 UTC, maksim25y commented on project/src/main/java/caselab/service/DocumentTypesService.java
> +
Убрал @Autowired и final

2024-10-04 09:34 UTC, ghost-of-endless requested changes

2024-10-04 09:34 UTC, ghost-of-endless commented on project/src/main/java/caselab/controller/DocumentTypesController.java
> +    }
Попробуй что-то типа такого:
```suggestion
@RestController
@RequiredArgsConstructor
@RequestMapping("/api/document_types")
public class DocumentTypesController {

    private final DocumentTypesService documentTypesService;
```

2024-10-04 09:34 UTC, ghost-of-endless commented on project/src/main/java/caselab/controller/DocumentTypesController.java
> +        return new ResponseEntity<>(documentTypesService.createDocumentType(documentType), HttpStatus.OK);
Для Ok не надо оборачивать в ResponseEntity:
```suggestion
        return documentTypesService.createDocumentType(documentType);
```

2024-10-04 09:38 UTC, GhostOfEndless commented on project/src/main/java/caselab/service/DocumentTypesService.java
> +
> Ты можешь повесить аннотацию @AllArgsConstructor на класс и вообще убрать конструктор, суть получается та же, но чуть более сладко) Ну и final с переменной надо не забыть убрать

Всё же правильнее делать зависимость `private final` и внедрять её через `@RequiredArgsConstructor`, потому что в классе ведь могут быть и другие поля, например какая-нибудь хешмапа, `ThreadPool` или `Semaphore`

2024-10-04 11:14 UTC, GhostOfEndless approved these changes

2024-10-04 11:15 UTC, merged