Feature/voting process
Alexandr-Kokorin/CaseLabProject pull request #42
Opened 2024-10-21 18:28 UTC by Alexandr-Kokorin

Голосование полностью работает, тестов еще нет

2024-10-21 19:04 UTC, ghost-of-endless commented on project/src/main/java/caselab/controller/voting_process/payload/VoteRequest.java
> +    long votingProcessId,
мб id лучше сделать обёрткой как и везде?

2024-10-21 19:04 UTC, GhostOfEndless commented on project/src/main/java/caselab/controller/voting_process/payload/VotingProcessRequest.java
> +    long deadline,
Логичнее, конечно, использовать что-то типа Period/Duration

2024-10-21 19:04 UTC, GhostOfEndless commented on project/src/main/java/caselab/controller/voting_process/payload/VotingProcessRequest.java
> +    long documentVersionId,
тут тоже обёртка

2024-10-21 19:04 UTC, GhostOfEndless commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +            applicationUserRepository.findByEmail(email).orElseThrow(() -> new UsernameNotFoundException(email));
emails.forEach()

2024-10-21 19:22 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/controller/voting_process/payload/VoteRequest.java
> +    long votingProcessId,
В этом нет смысла для айди, только лишняя проверка на null

2024-10-21 19:23 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/controller/voting_process/payload/VotingProcessRequest.java
> +    long deadline,
Логичнее, но в базе сделано long

2024-10-22 16:21 UTC, DennKK commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Почему бы в функцию поиск по id не вынести

2024-10-22 16:26 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
А смысл, она нигде больше не используется, только понимание кода усложнять необходимостью посмотреть куда-то еще, да и занимает она всего две строки, а функция будет 4

2024-10-22 16:28 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Поэтому считаю подобный рефакторинг крайне излишним, всё должно быть в меру

2024-10-22 16:35 UTC, DennKK commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Мне просто казалось, что читать `var votingProcess = finVotingProcessById(id)` проще, чем
```
var votingProcess = votingProcessRepository.findById(id)
            .orElseThrow(() -> new VotingProcessNotFoundException(id));
```
И как будто маленький приватный метод с очень красноречивым названием код в целом не усложняет, а делает его только более читаемым, несмотря на то, что сокращает всего две строки
```
private VotingProcess findAttributeById(Long id) {
        return votingProcess = votingProcessRepository.findById(id)
            .orElseThrow(() -> new VotingProcessNotFoundException(id));
    }
```
На твое усмотрение короче

2024-10-22 16:37 UTC, DennKK commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Ну и используется он в сервисе несколько раз все-таки

2024-10-22 16:40 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
А, он еще в получении, я туда вообще не смотрел, писал просто не я, тогда да, имеет смысл вынести

2024-10-22 16:41 UTC, Alexandr-Kokorin commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Но если бы был один раз, то всё же считаю, что не имеет смысла

2024-10-22 19:27 UTC, GhostOfEndless commented on project/src/main/java/caselab/service/voting_process/VotingProcessService.java
> +        var votingProcess = votingProcessRepository.findById(id)
Иногда такие методы действительно выносят, только называют уже get. find - возвращает Optional, get - возвращает сущность или бросает исключение

2024-10-22 21:01 UTC, ghost-of-endless approved these changes
Очень круто тест написал
TODO видел, поэтому на это внимание не обращал. В целом, именно так и должны выглядеть интеграционные тесты в проекте

2024-10-22 21:47 UTC, GhostOfEndless requested changes
Отправка уведомлений на почту

2024-10-29 15:01 UTC, closed without merging